### ISSUE TITLE
TypeScript導入

### ISSUE THREAD

**Issue by starlod** [starlod/MilleFeuille#28]
https://www.typescriptlang.org/#download-links

**Comment by starlod** [comment]
```
$ npm install -g typescript
```

**Comment by starlod** [comment]
Sublime Text 3 TypeScriptプラグイン
https://github.com/Microsoft/TypeScript-Sublime-Plugin

**Comment by starlod** [comment]
```
# app/config/config_dev.yml
services:        
      compileTypeScript:
        class: myApp\TypescriptBundle\Controller\TypescriptComiler
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 64 }
```

```
class TypescriptCompiler extends controller
{
    public function onKernelRequest(GetResponseEvent $event)
    {       
        // compile your TypeScript here
    }
}
```
